Assingment.PL/Controllers/DepartmentController.cs
using Assingment.BLL.Interfaces;
using Assingment.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assingment.PL.Controllers
{
    public class DepartmentController : Controller
    {
        private IunitOfWork _unitOfWork;

        public DepartmentController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }

        public IActionResult Index()
        {
            var departments = _unitOfWork.DepartmentRepository.GetAll();
            //ViewData["message"] = "All Departments";
            ViewBag.Message = "All Departments";
         
            return View(departments);
        }

        [HttpGet]
        public IActionResult Create()
        {
          
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.DepartmentRepository.Add(department);
                TempData["Message"] = "Department is Successfully Added";
                return RedirectToAction(nameof(Index));
            }
          

            return View(department);
        }

        public IActionResult Edit(int?  id)
        {
            if (id is null)
                return NotFound();
            var department = _unitOfWork.DepartmentRepository.GetById(id);
            if (department is null)
                return NotFound();

            return View(department);
        }
        [HttpPost]
        public IActionResult Edit(int id,Department department)
        {
            if (id != department.Id)
                return NotFound();
            if (ModelState.IsValid)
            {
                _unitOfWork.DepartmentRepository.Update(department);
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        public IActionResult Details(int? id)
        {
            if (id is null)
                return NotFound();
            var department = _unitOfWork.DepartmentRepository.GetById(id);
            if (department is null)
                return NotFound();

            return View(department);
        }
        [HttpGet]
        public IActionResult Delete(int id, Department department)
        {
            if (id != department.Id)
                return NotFound();
            _unitOfWork.DepartmentRepository.Remove(department);
            return RedirectToAction(nameof(Index));
        }
    }
}

Assingment.PL/Controllers/EmployeeController.cs
using Assingment.BLL.Interfaces;
using Assingment.BLL.Repositories;
using Assingment.DAL.Entities;
using Assingment.PL.Helper;
using Assingment.PL.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Assingment.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private IunitOfWork _unitOfWork;
        private IMapper _mapper;

        public EmployeeController(IunitOfWork  unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index(string SearchValue ="")
        {
            if(string.IsNullOrEmpty(SearchValue))
            {
                var employees = _unitOfWork.EmployeeRepository.GetAll();
                var mappedEmployees = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
                return View(mappedEmployees);
            }
            else
            {
                var employees = _unitOfWork.EmployeeRepository.Search(SearchValue);
                var mappedEmployees = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
                return View(mappedEmployees);
            }
           
        }

        public IActionResult Details(int id)
        {
            var employee = _unitOfWork.EmployeeRepository.GetById(id);
            if (employee is null)
                return NotFound();
           var employeeViewModel = _mapper.Map<EmployeeViewModel>(employee);
      
            return View(employeeViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Departments = _unitOfWork.DepartmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "imgs");
                var employee = _mapper.Map<Employee>(employeeViewModel);
                _unitOfWork.EmployeeRepository.Add(employee);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = _unitOfWork.DepartmentRepository.GetAll();
            return View(employeeViewModel);
    
        }
        public IActionResult Edit(int id )
        {
            var employee = _unitOfWork.EmployeeRepository.GetById(id);
            var employeeViewModel = _mapper.Map<EmployeeViewModel>(employee);
            ViewBag.Departments = _unitOfWork.DepartmentRepository.GetAll();
            return View(employeeViewModel);
        }
        [HttpPost]
        public IActionResult Edit(int id, EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                var employeeFromDatabase = _unitOfWork.EmployeeRepository.GetById(id);

                if (employeeViewModel.Image != null)
                {
                    if (employeeFromDatabase.ImageName != null)

                    {
                        string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "imgs");
                        string filePath = Path.Combine(folderPath, employeeFromDatabase.ImageName);
                        System.IO.File.Delete(filePath);
                    }

                    employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "imgs");

                }

                var employee  = _mapper.Map(employeeViewModel, employeeFromDatabase);
                _unitOfWork.EmployeeRepository.Update(employee);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = _unitOfWork.DepartmentRepository.GetAll();
            return View(employeeViewModel);
        }

       public IActionResult Delete(int id, EmployeeViewModel employeeViewModel)
        {
            var employee = _mapper.Map<Employee>(employeeViewModel)
 ;            _unitOfWork.EmployeeRepository.Remove(employee);
            return RedirectToAction(nameof(Index));
        }
   

    }
}

Assingment.PL/Controllers/RolesController.cs
using Assingment.DAL.Entities;
using Assingment.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assingment.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RolesController(RoleManager<ApplicationRole> roleManager ,UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
           _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
       public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ApplicationRole role)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var result = await _roleManager.CreateAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(String.Empty, error.Description);
                
                }catch(System.Exception)
                {
                    throw;
                }
            }
            return View(role);

        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null)
                return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role is null)
                return NotFound();

            return View(viewName, role);
        }

        public async Task<IActionResult> Update(string id, string viewName = "Update")
        {
            return await Details(id, "Update");
        }
        [HttpPost]
        public async Task<IActionResult> Update(string id, ApplicationRole role)
        {
            if (id != role.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var appRole = await _roleManager.FindByIdAsync(id);
                    appRole.Name = role.Name;
                    appRole.NormalizedName = role.Name.ToUpper();
                   
                    var result = await _roleManager.UpdateAsync(appRole);
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(String.Empty, error.Description);
                }

                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(User);
        }
        public async Task<IActionResult> Delete(String id, ApplicationRole role)
        {
            if (id != role.Id)
                return BadRequest();
            try
            {
                var appRole = await _roleManager.FindByIdAsync(id);
                var result = await _roleManager.DeleteAsync(appRole);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Errors = result.Errors;

            }
            catch (Exception ex)
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return BadRequest();
            ViewBag.RoleId = roleId;
            var users = new List<UserInRoleViewModel>();
            foreach (var user in _userManager.Users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };

                if(await _userManager.IsInRoleAsync(user,role.Name))
                    userInRole.IsSelected= true;
                else
                    userInRole.IsSelected= false;

                users.Add(userInRole);
            }
            return View(users);

        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleViewModel> users, string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return BadRequest();
            if (ModelState.IsValid)
            {
                foreach(var item in users)
                {
                    var user = await _userManager.FindByIdAsync(item.UserId);
                    if(user != null)
                    {
                        if (item.IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                            await _userManager.AddToRoleAsync(user, role.Name);
                        else if(!item.IsSelected && (await _userManager.IsInRoleAsync(user, role.Name)))
                            await _userManager.RemoveFromRoleAsync(user, role.Name);
                    }
                }
                return RedirectToAction(nameof(Update), new { id = roleId });
            }
            return View(users);
        }
    }
}

Assingment.PL/Controllers/UsersController.cs
using Assingment.DAL.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assingment.PL.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
      

        public UsersController(UserManager<ApplicationUser> userManager  )
        {
            _userManager = userManager;
        
        }

        public async Task<IActionResult> Index(string SearchValue ="")
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var users = _userManager.Users;
                return View(users);
            }
            else
            {
                var users = await _userManager.Users.Where(a => a.NormalizedEmail.Contains(SearchValue.ToUpper())).ToListAsync();
                return View(users);         
            }
        }


        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null)
                return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound();

            return View(viewName, user);                    
        }
        
        public async Task<IActionResult> Update(string id, string viewName = "Update")
        {
            return await Details(id, "Update");
        }
        [HttpPost]
        public async Task<IActionResult> Update(string id , ApplicationUser user)
        {
            if (id != user.Id)
                return BadRequest();
            if(ModelState.IsValid)
            {
                try
                {
                    var appUser = await _userManager.FindByIdAsync(id);
                    appUser.UserName = user.UserName;
                    appUser.NormalizedUserName = user.UserName.ToUpper();
                    appUser.PhoneNumber = user.PhoneNumber;
                    var result = await _userManager.UpdateAsync(appUser);
                    if(result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(String.Empty, error.Description);
                    }

                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(User);
        }
        public async Task<IActionResult> Delete(String id, ApplicationUser user)
        {
            if (id != user.Id)
                return BadRequest();
            try
            {
                var appUser = await _userManager.FindByIdAsync(id);
                var result = await _userManager.DeleteAsync(appUser);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Errors = result.Errors;
       
            }
            catch(Exception ex)
            {
                
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Assingment.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>

<head>
  <title>Creative Colorlib SignUp Form</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="application/x-javascript">
    addEventListener("load", function() {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>
  <!-- Custom Theme files -->
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
  <!-- //Custom Theme files -->
  <!-- web font -->
  <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
  <!-- //web font -->
</head>

<body>
  <!-- main -->
  <div class="main-w3layouts wrapper">
    <h1>@ViewData["Title"]</h1>
    @RenderBody()
    <!-- copyright -->
    <div class="colorlibcopy-agile">
      <p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
    </div>
    <!-- //copyright -->
    <ul class="colorlib-bubbles">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
  <!-- //main -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Assingment.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a class="btn btn-success" asp-action="Details" asp-route-id="@Model">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a class="btn btn-warning" asp-action="Update" asp-route-id="@Model">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Assingment.PL/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInMananger

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assingment.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assingment.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        @if( signInMananger.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                               <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        }
                     
                    </ul>
                    <ul class="navbar-nav  ">
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-light btn btn-danger" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Assingment.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>